package jdbc;
// Generated Apr 6, 2017 3:52:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private String genre;
     private Set movieGenres = new HashSet(0);

    public Genre() {
    }

	
    public Genre(String genre) {
        this.genre = genre;
    }
    public Genre(String genre, Set movieGenres) {
       this.genre = genre;
       this.movieGenres = movieGenres;
    }
   
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public Set getMovieGenres() {
        return this.movieGenres;
    }
    
    public void setMovieGenres(Set movieGenres) {
        this.movieGenres = movieGenres;
    }




}


