package jdbc;
// Generated Apr 6, 2017 3:52:08 AM by Hibernate Tools 4.3.1



/**
 * MovieGenre generated by hbm2java
 */
public class MovieGenre  implements java.io.Serializable {


     private Integer id;
     private Genre genre;
     private Movie movie;
     private String duplicateMovId;

    public MovieGenre() {
    }

    public MovieGenre(Genre genre, Movie movie, String duplicateMovId) {
       this.genre = genre;
       this.movie = movie;
       this.duplicateMovId = duplicateMovId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }
    public String getDuplicateMovId() {
        return this.duplicateMovId;
    }
    
    public void setDuplicateMovId(String duplicateMovId) {
        this.duplicateMovId = duplicateMovId;
    }




}


