package jdbc;
// Generated Apr 6, 2017 3:52:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private String movieId;
     private String title;
     private String description;
     private String runningTime;
     private int year;
     private double rating;
     private String watchStatus;
     private String favourite;
     private String poster;
     private String offlineLink;
     private String onlineLink;
     private String trailerLink;
     private Date addedDate;
     private String allMovieGenres;
     private Set movieGenres = new HashSet(0);

    public Movie() {
    }

    public Movie(String movieId) {
        this.movieId = movieId;
    }

	
    public Movie(String movieId, String title, String description, String runningTime, int year, double rating, String watchStatus, String favourite, String poster, String offlineLink, String onlineLink, String trailerLink, Date addedDate, String allMovieGenres) {
        this.movieId = movieId;
        this.title = title;
        this.description = description;
        this.runningTime = runningTime;
        this.year = year;
        this.rating = rating;
        this.watchStatus = watchStatus;
        this.favourite = favourite;
        this.poster = poster;
        this.offlineLink = offlineLink;
        this.onlineLink = onlineLink;
        this.trailerLink = trailerLink;
        this.addedDate = addedDate;
        this.allMovieGenres = allMovieGenres;
    }
    public Movie(String movieId, String title, String description, String runningTime, int year, double rating, String watchStatus, String favourite, String poster, String offlineLink, String onlineLink, String trailerLink, Date addedDate, String allMovieGenres, Set movieGenres) {
       this.movieId = movieId;
       this.title = title;
       this.description = description;
       this.runningTime = runningTime;
       this.year = year;
       this.rating = rating;
       this.watchStatus = watchStatus;
       this.favourite = favourite;
       this.poster = poster;
       this.offlineLink = offlineLink;
       this.onlineLink = onlineLink;
       this.trailerLink = trailerLink;
       this.addedDate = addedDate;
       this.allMovieGenres = allMovieGenres;
       this.movieGenres = movieGenres;
    }
   
    public String getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRunningTime() {
        return this.runningTime;
    }
    
    public void setRunningTime(String runningTime) {
        this.runningTime = runningTime;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public double getRating() {
        return this.rating;
    }
    
    public void setRating(double rating) {
        this.rating = rating;
    }
    public String getWatchStatus() {
        return this.watchStatus;
    }
    
    public void setWatchStatus(String watchStatus) {
        this.watchStatus = watchStatus;
    }
    public String getFavourite() {
        return this.favourite;
    }
    
    public void setFavourite(String favourite) {
        this.favourite = favourite;
    }
    public String getPoster() {
        return this.poster;
    }
    
    public void setPoster(String poster) {
        this.poster = poster;
    }
    public String getOfflineLink() {
        return this.offlineLink;
    }
    
    public void setOfflineLink(String offlineLink) {
        this.offlineLink = offlineLink;
    }
    public String getOnlineLink() {
        return this.onlineLink;
    }
    
    public void setOnlineLink(String onlineLink) {
        this.onlineLink = onlineLink;
    }

    public String getTrailerLink() {
        return trailerLink;
    }

    public void setTrailerLink(String trailerLink) {
        this.trailerLink = trailerLink;
    }
    
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public String getAllMovieGenres() {
        return this.allMovieGenres;
    }
    
    public void setAllMovieGenres(String allMovieGenres) {
        this.allMovieGenres = allMovieGenres;
    }
    public Set getMovieGenres() {
        return this.movieGenres;
    }
    
    public void setMovieGenres(Set movieGenres) {
        this.movieGenres = movieGenres;
    }




}


